<?php

return [
    /*
    |--------------------------------------------------------------------------
    | Various Image Configuration by model
    |--------------------------------------------------------------------------
    |
    | Here you may configure as many model based configuration such as supported_format
    | maximum_file_size in MB,temporary_image_storage_path,image_resolution,thumb_image_resolution,default_image_path
    |
     */

    'thumbnail' => [
        'supported_format'             => 'jpg,png,jpeg',
        'fileSize'                     => 2,
        'temporary_image_storage_path' => 'uploads'.DIRECTORY_SEPARATOR.'tempimage'.DIRECTORY_SEPARATOR.'thumbnails',
        'storage_path'                 => 'uploads/thumbnails',
        'image_resolution'             => '182x100',
        's3_location'                  => 'images/videos/thumbnails/'.date("Y").'/'.date("m").'/',
        's3_fetch_location'            => 'images/videos/thumbnails/',
    ],
    'admin_user_profile_image' => [
        'supported_format'             => 'jpg,png,jpeg',
        'fileSize'                     => 2,
        'temporary_image_storage_path' => 'uploads'.DIRECTORY_SEPARATOR.'tempimage'.DIRECTORY_SEPARATOR.'admin_user_profile_images',
        'storage_path'                 => 'uploads/profile',
        's3_location'                  => 'images/admin_profile_images/'.date("Y").'/'.date("m").'/',
        'image_resolution'             => '400x300',
    ],
    'customer_profile_image' => [
        'supported_format'             => 'jpg,png,jpeg',
        'fileSize'                     => 2,
        'temporary_image_storage_path' => 'uploads'.DIRECTORY_SEPARATOR.'tempimage'.DIRECTORY_SEPARATOR.'customer_profile_images',
        'storage_path'                 => 'uploads/profile',
        's3_location'                  => 'images/customer_profile_images/'.date("Y").'/'.date("m").'/',
        'image_resolution'             => '400x300',
    ],
    'category_image' => [
        'supported_format'             => 'jpg,png,jpeg',
        'fileSize'                     => 2,
        'temporary_image_storage_path' => 'uploads'.DIRECTORY_SEPARATOR.'tempimage'.DIRECTORY_SEPARATOR.'category_images',
        'storage_path'                 => 'uploads/category_images',
        'image_resolution'             => '1500x730',
        's3_location'                  => 'images/category_images/'.date("Y").'/'.date("m").'/',
        's3_fetch_location'            => 'images/category_images/',
    ],
    'season_image' => [
        'supported_format'             => 'jpg,png,jpeg',
        'fileSize'                     => 2,
        'temporary_image_storage_path' => 'uploads'.DIRECTORY_SEPARATOR.'tempimage'.DIRECTORY_SEPARATOR.'season_image',
        'storage_path'                 => 'uploads/season_image',
        'image_resolution'             => '600x300',
        's3_location'                  => 'images/season_image/'.date("Y").'/'.date("m").'/',
        's3_fetch_location'            => 'images/season_image/',
    ],
    'footer_image' => [
        'supported_format'             => 'jpg,png,jpeg',
        'fileSize'                     => 2,
        'temporary_image_storage_path' => 'uploads'.DIRECTORY_SEPARATOR.'tempimage'.DIRECTORY_SEPARATOR.'footer_image',
        'storage_path'                 => 'uploads/footer_image',
        'image_resolution' => '1300x300',
        's3_location'                  => 'images/footer_image/'.date("Y").'/'.date("m").'/',
        's3_fetch_location'            => 'images/footer_image/',
    ],
    'banner_image' => [
        'supported_format'             => 'jpg,png,jpeg',
        'fileSize'                     => 2,
        'temporary_image_storage_path' => 'uploads'.DIRECTORY_SEPARATOR.'tempimage'.DIRECTORY_SEPARATOR.'banner_images',
        'storage_path'                 => 'uploads/banner_images',
        'image_resolution' => '1500x560',
        's3_location'                  => 'images/banner_images/'.date("Y").'/'.date("m").'/',
        's3_fetch_location'            => 'images/banner_images/',
    ],
    'mobile_bannerimage' => [
        'supported_format' => 'jpg,png,jpeg',
        'fileSize' => 2,
        'temporary_image_storage_path' => 'uploads' . DIRECTORY_SEPARATOR . 'tempimage' . DIRECTORY_SEPARATOR . 'banner_images',
        'storage_path' => 'uploads/banner_images',
        'image_resolution' => '380x500',
        's3_location' => 'images/banner_images/' . date("Y") . '/' . date("m") . '/',
        's3_fetch_location' => 'images/banner_images/',
    ],
    'live_image' => [
        'supported_format' => 'jpg,png,jpeg',
        'fileSize' => 2,
        'temporary_image_storage_path' => 'uploads' . DIRECTORY_SEPARATOR . 'tempimage' . DIRECTORY_SEPARATOR . 'live_image',
        'storage_path' => 'uploads/live_image',
        'image_resolution' => '350x250',
        's3_location' => 'images/live_image/' . date("Y") . '/' . date("m") . '/',
        's3_fetch_location' => 'images/live_image/',
    ],
    'web_image' => [
        'supported_format'             => 'jpg,png,jpeg',
        'fileSize'                     => 2,
        'temporary_image_storage_path' => 'uploads'.DIRECTORY_SEPARATOR.'tempimage'.DIRECTORY_SEPARATOR.'mobile_image',
        'storage_path'                 => 'uploads/mobile_image',
        'image_resolution' => '1500x730',
        's3_location'                  => 'images/mobile_image/'.date("Y").'/'.date("m").'/',
        's3_fetch_location'            => 'images/mobile_image/',
    ],
    'mobile_image' => [
        'supported_format'             => 'jpg,png,jpeg',
        'fileSize'                     => 2,
        'temporary_image_storage_path' => 'uploads'.DIRECTORY_SEPARATOR.'tempimage'.DIRECTORY_SEPARATOR.'mobile_image',
        'storage_path'                 => 'uploads/mobile_image',
        'image_resolution' => '540x960',
        's3_location'                  => 'images/mobile_image/'.date("Y").'/'.date("m").'/',
        's3_fetch_location'            => 'images/mobile_image/',
    ],
    'subtitle' => [
        'supported_format' => 'mpga,mp3,audio/mp3,audio/mpeg,mpeg,mp2,mp2a,m2a,m3a,bin',
        'fileSize' => 1000,
        'temporary_storage_path' => 'app/tempimage/subtitle',
        'storage_path' => 'contus/mp3',
        'is_file' => 1,
    ],
    'posters' => [
        'supported_format'             => 'jpg,png,jpeg',
        'fileSize'                     => 2,
        'temporary_image_storage_path' => 'uploads'.DIRECTORY_SEPARATOR.'tempimage'.DIRECTORY_SEPARATOR.'posters',
        'storage_path'                 => 'uploads/posters',
        'image_resolution'             => '400x300',
        's3_location'                  => 'images/videos/posters/'.date("Y").'/'.date("m").'/',
        's3_fetch_location'            => 'images/videos/posters/',
    ],
    'mobile_posters' => [
        'supported_format' => 'jpg,png,jpeg',
        'fileSize' => 2,
        'temporary_image_storage_path' => 'uploads' . DIRECTORY_SEPARATOR . 'tempimage' . DIRECTORY_SEPARATOR . 'posters',
        'storage_path' => 'uploads/posters',
        'image_resolution' => '380x500',
        's3_location' => 'images/videos/posters/' . date("Y") . '/' . date("m") . '/',
        's3_fetch_location' => 'images/videos/posters/',
    ],
    'cast_images' => [
        'supported_format'             => 'jpg,png,jpeg',
        'fileSize'                     => 2,
        'temporary_image_storage_path' => 'uploads'.DIRECTORY_SEPARATOR.'tempimage'.DIRECTORY_SEPARATOR.'cast_images',
        'storage_path'                 => 'uploads/cast_images',
        'image_resolution'             => '400x300',
    ],
    'artist_image' => [
        'supported_format' => 'jpg,png,jpeg',
        'fileSize' => 2,
        'temporary_image_storage_path' => 'uploads' . DIRECTORY_SEPARATOR . 'tempimage' . DIRECTORY_SEPARATOR . 'artist_images',
        'storage_path' => 'uploads/artist_images',
        'image_resolution' => '400x300',
        's3_location' => 'audios/images/artist_images/' . date("Y") . '/' . date("m") . '/',
        's3_fetch_location' => 'audios/images/artist_images/',
    ],
    'album_image' => [
        'supported_format' => 'jpg,png,jpeg',
        'fileSize' => 2,
        'temporary_image_storage_path' => 'uploads' . DIRECTORY_SEPARATOR . 'tempimage' . DIRECTORY_SEPARATOR . 'thumbnails',
        'storage_path' => 'uploads/thumbnails',
        'image_resolution' => '400x300',
        's3_location' => 'audios/images/album_images/' . date("Y") . '/' . date("m") . '/',
        's3_fetch_location' => 'audios/images/album_images/',
    ],
    'audio_image' => [
        'supported_format' => 'jpg,png,jpeg',
        'fileSize' => 2,
        'temporary_image_storage_path' => 'uploads' . DIRECTORY_SEPARATOR . 'tempimage' . DIRECTORY_SEPARATOR . 'thumbnails',
        'storage_path' => 'uploads/thumbnails',
        'image_resolution' => '400x300',
        's3_location' => 'audios/images/audio_images/' . date("Y") . '/' . date("m") . '/',
        's3_fetch_location' => 'audios/images/audio_images/',
    ],
    'ads' => [
        'supported_format' => 'text/xml',
        'fileSize' => 20,
        'temporary_image_storage_path' => 'uploads' . DIRECTORY_SEPARATOR . 'ads' . DIRECTORY_SEPARATOR . 'xml',
        'storage_path' => 'uploads/thumbnails',
        'image_resolution' => '400x300',
        's3_location' => 'ads/xml/' . date("Y") . '/' . date("m") . '/',
        's3_fetch_location' => 'ads/xml/',
    ],
];
