<?php


use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Contus\Cms\Models\StaticPages;
use Illuminate\Support\Facades\DB;

class StaticPagesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $existCount = DB::table('static_pages')->count();
        if($existCount <= 0) {
            DB::unprepared("ALTER TABLE static_pages AUTO_INCREMENT = 1;");
            StaticPages::insert([
                    [
                        'title' => 'About Us',
                        'slug' => 'about-us',
                        'content' => '<p style="color: #333333; font-family: \'Open Sans\', sans-serif; font-size: 14px; box-sizing: border-box; margin: 0px;">Contus VOD is a ready-made online video platform that helps broadcasters, online video streaming websites, enterprises etc to upload, convert, store, manage and stream video content on the Internet.</p>
<p style="color: #333333; font-family: \'Open Sans\', sans-serif; font-size: 14px; box-sizing: border-box; margin: 0px;">&nbsp;</p>
<p style="color: #333333; font-family: \'Open Sans\', sans-serif; font-size: 14px; box-sizing: border-box; margin: 0px;">Providing the ability to deliver contents across smartphones, smart TVs and connected devices, our OTT streaming solution comes packed with provisions for encoding, decoding, streaming, publishing contents in various delivery networks and channels.</p>
<p style="color: #333333; font-family: \'Open Sans\', sans-serif; font-size: 14px; box-sizing: border-box; margin: 0px;">&nbsp;</p>
<p style="color: #333333; font-family: \'Open Sans\', sans-serif; font-size: 14px; box-sizing: border-box; margin: 0px;">Render live videos with no time lapse using our live streaming solution. We can help you encode to digitize your content, get it to media publishers and deliver it across a content delivery network. Our video on demand software\'s encoding makes your video contents compatible to be played via devices with any hardware capability.</p>',
                        'is_active'  => 1,
                        'creator_id' => 0,
                        'updator_id' => 0,
                        'created_at' => Carbon::now()->toDateTimeString(),
                        'updated_at' => Carbon::now()->toDateTimeString(),
                    ],
                    [
                        'title' => 'Terms and Conditions',
                        'slug' => 'terms-and-conditions',
                        'content' => '<p style="box-sizing: border-box; margin: 0px; color: #333333; font-family: \'Open Sans\', sans-serif; font-size: 14px;"><span style="box-sizing: border-box; font-weight: bold;">Account:</span>&nbsp;</p>
<p style="box-sizing: border-box; margin: 0px; color: #333333; font-family: \'Open Sans\', sans-serif; font-size: 14px;">&nbsp;</p>
<p style="box-sizing: border-box; margin: 0px; color: #333333; font-family: \'Open Sans\', sans-serif; font-size: 14px;">In order to use certain features of the Website, you must register for an account. You may be asked to provide a password in connection with your account. You are solely responsible for maintaining the confidentiality of your account and password, and you agree to accept responsibility for all activities that occur under your account or password.&nbsp;</p>
<p style="box-sizing: border-box; margin: 0px; color: #333333; font-family: \'Open Sans\', sans-serif; font-size: 14px;">&nbsp;</p>
<p style="box-sizing: border-box; margin: 0px; color: #333333; font-family: \'Open Sans\', sans-serif; font-size: 14px;">The information you provide to Vplayed, whether at registration or at any other time, will be true, accurate, current, and complete. You should also ensure that this information is kept accurate and up-to-date at all times. If you have reason to believe that your account is no longer secure (e.g., in the event of a loss, theft or unauthorized disclosure or use of your account ID or password), then you should immediately notify Vplayed at info@contus.in. You may be liable for the losses incurred by Vplayed or others due to any unauthorized use of your Website account</p>
<p style="box-sizing: border-box; margin: 0px; color: #333333; font-family: \'Open Sans\', sans-serif; font-size: 14px;">&nbsp;</p>
<p style="box-sizing: border-box; margin: 0px; color: #333333; font-family: \'Open Sans\', sans-serif; font-size: 14px;"><span style="box-sizing: border-box; font-weight: bold;">Modification of the Terms.</span></p>
<p style="box-sizing: border-box; margin: 0px; color: #333333; font-family: \'Open Sans\', sans-serif; font-size: 14px;">&nbsp;</p>
<p style="box-sizing: border-box; margin: 0px; color: #333333; font-family: \'Open Sans\', sans-serif; font-size: 14px;">Vplayed reserves the right, at our discretion, to change, modify, add, or remove portions of the Terms at any time. Please check the Terms and any Guidelines periodically for changes.&nbsp;</p>
<p style="box-sizing: border-box; margin: 0px; color: #333333; font-family: \'Open Sans\', sans-serif; font-size: 14px;">&nbsp;</p>
<p style="box-sizing: border-box; margin: 0px; color: #333333; font-family: \'Open Sans\', sans-serif; font-size: 14px;">Your continued use of the Website after the posting of changes constitutes your binding acceptance of such changes. For any major changes to the Terms, Vplayed will make reasonable effort to provide notice to you by an email notification to the address associated with your account or by posting a notice on the Website.</p>
<p style="box-sizing: border-box; margin: 0px; color: #333333; font-family: \'Open Sans\', sans-serif; font-size: 14px;">&nbsp;</p>
<p style="box-sizing: border-box; margin: 0px; color: #333333; font-family: \'Open Sans\', sans-serif; font-size: 14px;">Such amended terms will be effective against you on the earlier of (i) your actual notice of such changes and (ii) thirty days after Vplayed makes reasonable attempt to provide you such notice.&nbsp;</p>
<p style="box-sizing: border-box; margin: 0px; color: #333333; font-family: \'Open Sans\', sans-serif; font-size: 14px;">&nbsp;</p>
<p style="box-sizing: border-box; margin: 0px; color: #333333; font-family: \'Open Sans\', sans-serif; font-size: 14px;">Disputes arising under these Terms will be resolved in accordance with the version of the Terms in place at the time the dispute arose.</p>
<p style="box-sizing: border-box; margin: 0px; color: #333333; font-family: \'Open Sans\', sans-serif; font-size: 14px;">&nbsp;</p>
<p style="box-sizing: border-box; margin: 0px; color: #333333; font-family: \'Open Sans\', sans-serif; font-size: 14px;">That the Company shall be entitled to make policy declarations from time to time pertaining to matters and may alter the same from time to time at its sole discretion. &nbsp;All such policy decisions of the Company shall be binding on user and shall override this Agreement to that extent.</p>
<p style="box-sizing: border-box; margin: 0px; color: #333333; font-family: \'Open Sans\', sans-serif; font-size: 14px;">&nbsp;</p>
<p style="box-sizing: border-box; margin: 0px; color: #333333; font-family: \'Open Sans\', sans-serif; font-size: 14px;"><span style="box-sizing: border-box; font-weight: bold;">Proprietary Materials &amp; Licences</span></p>
<p style="box-sizing: border-box; margin: 0px; color: #333333; font-family: \'Open Sans\', sans-serif; font-size: 14px;">&nbsp;</p>
<p style="box-sizing: border-box; margin: 0px; color: #333333; font-family: \'Open Sans\', sans-serif; font-size: 14px;"><span style="box-sizing: border-box; font-weight: bold;">Proprietary Materials:</span></p>
<p style="box-sizing: border-box; margin: 0px; color: #333333; font-family: \'Open Sans\', sans-serif; font-size: 14px;">&nbsp;</p>
<p style="box-sizing: border-box; margin: 0px; color: #333333; font-family: \'Open Sans\', sans-serif; font-size: 14px;">The Website is owned and operated by Vplayed. The visual interfaces, graphics, design, compilation, information, computer code (including source code or object code), software, services, content, educational videos and exercises, and all other elements of the Website are protected by Indian and international copyright, patent, and trademark laws, international conventions, and other applicable laws governing intellectual property and proprietary rights.&nbsp;</p>
<p style="box-sizing: border-box; margin: 0px; color: #333333; font-family: \'Open Sans\', sans-serif; font-size: 14px;">&nbsp;</p>
<p style="box-sizing: border-box; margin: 0px; color: #333333; font-family: \'Open Sans\', sans-serif; font-size: 14px;"><span style="box-sizing: border-box; font-weight: bold;">Licensed Educational Content:</span></p>
<p style="box-sizing: border-box; margin: 0px; color: #333333; font-family: \'Open Sans\', sans-serif; font-size: 14px;">&nbsp;</p>
<p style="box-sizing: border-box; margin: 0px; color: #333333; font-family: \'Open Sans\', sans-serif; font-size: 14px;">Vplayed may make available on the Website certain educational videos, exercises, and related supplementary materials that are owned by Vplayed or its third-party licensors.&nbsp;</p>
<p style="box-sizing: border-box; margin: 0px; color: #333333; font-family: \'Open Sans\', sans-serif; font-size: 14px;">&nbsp;</p>
<p style="box-sizing: border-box; margin: 0px; color: #333333; font-family: \'Open Sans\', sans-serif; font-size: 14px;">Vplayed grants you a non-exclusive, non-transferable right to access and use the Licensed Educational Content as made available on the Website by Vplayed solely for your personal, non-commercial purposes. Unless expressly indicated on the Website that a particular item of Licensed Educational Content is made available to Users under other license terms, you may not download, distribute, sell, lease, modify, or otherwise provide access to the Licensed Educational Content to any third party.</p>
<p style="box-sizing: border-box; margin: 0px; color: #333333; font-family: \'Open Sans\', sans-serif; font-size: 14px;">&nbsp;</p>
<p style="box-sizing: border-box; margin: 0px; color: #333333; font-family: \'Open Sans\', sans-serif; font-size: 14px;"><span style="box-sizing: border-box; font-weight: bold;">Other Licenses:</span></p>
<p style="box-sizing: border-box; margin: 0px; color: #333333; font-family: \'Open Sans\', sans-serif; font-size: 14px;">&nbsp;</p>
<p style="box-sizing: border-box; margin: 0px; color: #333333; font-family: \'Open Sans\', sans-serif; font-size: 14px;">In certain cases, Vplayed or its licensors may make available Licensed Educational Content under Other license terms. By using, downloading, or otherwise accessing such Licensed Educational Content, You agree to comply fully with all the terms and conditions of such Other License.</p>
<p style="box-sizing: border-box; margin: 0px; color: #333333; font-family: \'Open Sans\', sans-serif; font-size: 14px;">&nbsp;</p>
<p style="box-sizing: border-box; margin: 0px; color: #333333; font-family: \'Open Sans\', sans-serif; font-size: 14px;"><span style="box-sizing: border-box; font-weight: bold;">Termination.</span></p>
<p style="box-sizing: border-box; margin: 0px; color: #333333; font-family: \'Open Sans\', sans-serif; font-size: 14px;">&nbsp;</p>
<p style="box-sizing: border-box; margin: 0px; color: #333333; font-family: \'Open Sans\', sans-serif; font-size: 14px;"><span style="box-sizing: border-box; font-weight: bold;">Termination by Vplayed:</span></p>
<p style="box-sizing: border-box; margin: 0px; color: #333333; font-family: \'Open Sans\', sans-serif; font-size: 14px;">&nbsp;</p>
<p style="box-sizing: border-box; margin: 0px; color: #333333; font-family: \'Open Sans\', sans-serif; font-size: 14px;">Vplayed, in its sole discretion, for any or no reason, and without penalty, may terminate any account (or any part thereof) you may have with Vplayed or your use of the Website and remove and discard all or any part of your account, User profile, and User Content, at any time.&nbsp;</p>
<p style="box-sizing: border-box; margin: 0px; color: #333333; font-family: \'Open Sans\', sans-serif; font-size: 14px;">&nbsp;</p>
<p style="box-sizing: border-box; margin: 0px; color: #333333; font-family: \'Open Sans\', sans-serif; font-size: 14px;">Vplayed may also in its sole discretion and at any time discontinue providing access to the Website, or any part thereof, with or without notice. You agree that any termination of your access to the Website or any account you may have, or portion thereof, may be affected without prior notice, and You agree that Vplayed will not be liable to you or any third party for any such termination. Any suspected fraudulent, abusive or illegal activity may be referred to appropriate law enforcement authorities.&nbsp;</p>
<p style="box-sizing: border-box; margin: 0px; color: #333333; font-family: \'Open Sans\', sans-serif; font-size: 14px;">&nbsp;</p>
<p style="box-sizing: border-box; margin: 0px; color: #333333; font-family: \'Open Sans\', sans-serif; font-size: 14px;">These remedies are in addition to any other remedies Vplayed may have at law or in equity. As discussed herein, Vplayed does not permit copyright, trademarks, or other intellectual property infringing activities on the Website, and will terminate access to the Website, and remove all User Content or other content submitted, by any Users who are found to be repeat infringers.</p>
<p style="box-sizing: border-box; margin: 0px; color: #333333; font-family: \'Open Sans\', sans-serif; font-size: 14px;">&nbsp;</p>
<p style="box-sizing: border-box; margin: 0px; color: #333333; font-family: \'Open Sans\', sans-serif; font-size: 14px;"><span style="box-sizing: border-box; font-weight: bold;">Termination by You:</span></p>
<p style="box-sizing: border-box; margin: 0px; color: #333333; font-family: \'Open Sans\', sans-serif; font-size: 14px;">&nbsp;</p>
<p style="box-sizing: border-box; margin: 0px; color: #333333; font-family: \'Open Sans\', sans-serif; font-size: 14px;">If you are dissatisfied with (i) the Website, (ii) any term of these Terms of Service, (iii) Guidelines, (iv) any policy or practice of Vplayed in operating the Website, or (v) any content or information transmitted through the Website, you can terminate your account. You may terminate at any time by deleting your login account with the Website and discontinuing use of any and all parts of the Website.</p>
<p style="box-sizing: border-box; margin: 0px; color: #333333; font-family: \'Open Sans\', sans-serif; font-size: 14px;">&nbsp;</p>
<p style="box-sizing: border-box; margin: 0px; color: #333333; font-family: \'Open Sans\', sans-serif; font-size: 14px;"><span style="box-sizing: border-box; font-weight: bold;">Prohibited Conduct:</span></p>
<p style="box-sizing: border-box; margin: 0px; color: #333333; font-family: \'Open Sans\', sans-serif; font-size: 14px;">&nbsp;</p>
<p style="box-sizing: border-box; margin: 0px; color: #333333; font-family: \'Open Sans\', sans-serif; font-size: 14px;"><span style="box-sizing: border-box; font-weight: bold;">YOU AGREE NOT TO:</span></p>
<p style="box-sizing: border-box; margin: 0px; color: #333333; font-family: \'Open Sans\', sans-serif; font-size: 14px;">&nbsp;</p>
<p style="box-sizing: border-box; margin: 0px; color: #333333; font-family: \'Open Sans\', sans-serif; font-size: 14px;">1. Use the Website for any commercial use or purpose unless expressly permitted by Vplayed in writing, it being understood that the Website and related services are intended for personal, non-commercial use only;</p>
<p style="box-sizing: border-box; margin: 0px; color: #333333; font-family: \'Open Sans\', sans-serif; font-size: 14px;">&nbsp;</p>
<p style="box-sizing: border-box; margin: 0px; color: #333333; font-family: \'Open Sans\', sans-serif; font-size: 14px;">2. Impersonate any person or entity, falsely claim an affiliation with any person or entity, or access the Website accounts of others without permission, or perform any other fraudulent activity;</p>
<p style="box-sizing: border-box; margin: 0px; color: #333333; font-family: \'Open Sans\', sans-serif; font-size: 14px;">&nbsp;</p>
<p style="box-sizing: border-box; margin: 0px; color: #333333; font-family: \'Open Sans\', sans-serif; font-size: 14px;">3. Delete the copyright or other proprietary rights notices on the Website or on any Licensed Educational Content, Licensed Educational Code, or User Content;</p>
<p style="box-sizing: border-box; margin: 0px; color: #333333; font-family: \'Open Sans\', sans-serif; font-size: 14px;">&nbsp;</p>
<p style="box-sizing: border-box; margin: 0px; color: #333333; font-family: \'Open Sans\', sans-serif; font-size: 14px;">4. Assert, or authorize, assist, or encourage any third party to assert, against Vplayed or any of its affiliates or licensors any patent infringement or other intellectual property infringement claim regarding any Licensed Educational Content, Licensed Educational Code, or User Content You have used, submitted, or otherwise made available on or through the Website;</p>
<p style="box-sizing: border-box; margin: 0px; color: #333333; font-family: \'Open Sans\', sans-serif; font-size: 14px;">&nbsp;</p>
<p style="box-sizing: border-box; margin: 0px; color: #333333; font-family: \'Open Sans\', sans-serif; font-size: 14px;">5. Make unsolicited offers, advertisements, proposals, or send junk mail or spam to other Users of the Website (including, but not limited to, unsolicited advertising, promotional materials, or other solicitation material, bulk mailing of commercial advertising, chain mail, informational announcements, charity requests, and petitions for signatures);</p>
<p style="box-sizing: border-box; margin: 0px; color: #333333; font-family: \'Open Sans\', sans-serif; font-size: 14px;">&nbsp;</p>
<p style="box-sizing: border-box; margin: 0px; color: #333333; font-family: \'Open Sans\', sans-serif; font-size: 14px;">6. Use the Website for any illegal purpose, or in violation of any local, state, national, or international law, including, without limitation, laws governing intellectual property and other proprietary rights, data protection and privacy;</p>
<p style="box-sizing: border-box; margin: 0px; color: #333333; font-family: \'Open Sans\', sans-serif; font-size: 14px;">&nbsp;</p>
<p style="box-sizing: border-box; margin: 0px; color: #333333; font-family: \'Open Sans\', sans-serif; font-size: 14px;">7. Defame, harass, abuse, threaten or defraud Users of the Website, or collect, or attempt to collect, personal information about Users or third parties without their consent;</p>
<p style="box-sizing: border-box; margin: 0px; color: #333333; font-family: \'Open Sans\', sans-serif; font-size: 14px;">&nbsp;</p>
<p style="box-sizing: border-box; margin: 0px; color: #333333; font-family: \'Open Sans\', sans-serif; font-size: 14px;">8. Remove, circumvent, disable, damage or otherwise interfere with security-related features of the Website, Licensed Educational Content, Licensed Educational Code, or User Content, features &nbsp;that prevent or restrict use or copying of any content accessible through the Website, or features that enforce limitations on the use of the Website, Licensed Educational Content, Licensed Educational Code, or User Content;</p>
<p style="box-sizing: border-box; margin: 0px; color: #333333; font-family: \'Open Sans\', sans-serif; font-size: 14px;">&nbsp;</p>
<p style="box-sizing: border-box; margin: 0px; color: #333333; font-family: \'Open Sans\', sans-serif; font-size: 14px;">9. Reverse engineer, decompile, disassemble or otherwise attempt to discover the source code of the Website or any part thereof, except and only to the extent that such activity is expressly permitted by applicable law notwithstanding this limitation;</p>
<p style="box-sizing: border-box; margin: 0px; color: #333333; font-family: \'Open Sans\', sans-serif; font-size: 14px;">&nbsp;</p>
<p style="box-sizing: border-box; margin: 0px; color: #333333; font-family: \'Open Sans\', sans-serif; font-size: 14px;">10. Modify, adapt, translate or create derivative works based upon the Website or any part thereof, except and only to the extent expressly permitted by Vplayed herein or to the extent the foregoing restriction is expressly prohibited by applicable law;</p>
<p style="box-sizing: border-box; margin: 0px; color: #333333; font-family: \'Open Sans\', sans-serif; font-size: 14px;">&nbsp;</p>
<p style="box-sizing: border-box; margin: 0px; color: #333333; font-family: \'Open Sans\', sans-serif; font-size: 14px;">11. Intentionally interfere with or damage operation of the Website or any user&rsquo;s enjoyment of it, by any means, including without limitation by participation in any denial-of-service type attacks or by uploading or otherwise disseminating viruses, adware, spyware, worms, or other malicious code.</p>
<p style="box-sizing: border-box; margin: 0px; color: #333333; font-family: \'Open Sans\', sans-serif; font-size: 14px;">&nbsp;</p>
<p style="box-sizing: border-box; margin: 0px; color: #333333; font-family: \'Open Sans\', sans-serif; font-size: 14px;">Note: By clicking the &ldquo;I Accept&rdquo; button, you are agreeing to the Terms and Conditions as well as Privacy Policy.</p>',
                        'is_active'  => 1,
                        'creator_id' => 0,
                        'updator_id' => 0,
                        'created_at' => Carbon::now()->toDateTimeString(),
                        'updated_at' => Carbon::now()->toDateTimeString(),
                    ],
                    [
                        'title' => 'Privacy Policy',
                        'slug' => 'privacy-policy',
                        'content' => '<p style="color: #333333; font-family: \'Open Sans\', sans-serif; font-size: 14px; box-sizing: border-box; margin: 0px;"><span style="box-sizing: border-box; font-weight: bold;">Overview</span></p>
<p style="color: #333333; font-family: \'Open Sans\', sans-serif; font-size: 14px; box-sizing: border-box; margin: 0px;">&nbsp;</p>
<p style="color: #333333; font-family: \'Open Sans\', sans-serif; font-size: 14px; box-sizing: border-box; margin: 0px;">We take your privacy seriously and are committed to protecting your right to privacy as a user of our website. We have made every effort to ensure your information is secure. This privacy policy information covers what information is collected, what we do with it, and what you can do about it. You can use this information to make your decisions about your privacy.</p>
<p style="color: #333333; font-family: \'Open Sans\', sans-serif; font-size: 14px; box-sizing: border-box; margin: 0px;">&nbsp;</p>
<p style="color: #333333; font-family: \'Open Sans\', sans-serif; font-size: 14px; box-sizing: border-box; margin: 0px;"><span style="box-sizing: border-box; font-weight: bold;">User ID and Password</span></p>
<p style="color: #333333; font-family: \'Open Sans\', sans-serif; font-size: 14px; box-sizing: border-box; margin: 0px;">&nbsp;</p>
<p style="color: #333333; font-family: \'Open Sans\', sans-serif; font-size: 14px; box-sizing: border-box; margin: 0px;">By entering into this Agreement, You acknowledge and agree that Your user ID and password ("Participant Account") is for Your exclusive use only.&nbsp;<span style="box-sizing: border-box; font-weight: bold;">Use or sharing of Your Participant Account with another user is not permitted and is cause for immediate blocking of Your access to the Website, the Services and the Content, the Lecture videos, and termination of this Agreement.</span></p>
<p style="color: #333333; font-family: \'Open Sans\', sans-serif; font-size: 14px; box-sizing: border-box; margin: 0px;">&nbsp;</p>
<p style="color: #333333; font-family: \'Open Sans\', sans-serif; font-size: 14px; box-sizing: border-box; margin: 0px;">You agree that You are solely responsible for maintaining the confidentiality of Your Participant Account and for all activities that occur under it.</p>
<p style="color: #333333; font-family: \'Open Sans\', sans-serif; font-size: 14px; box-sizing: border-box; margin: 0px;">&nbsp;</p>
<p style="color: #333333; font-family: \'Open Sans\', sans-serif; font-size: 14px; box-sizing: border-box; margin: 0px;">You agree to immediately notify our Customer Support Team at support@contus.in if You become aware of or have reason to believe that there is any unauthorized use of Your Participant Account. You also agree to take all reasonable steps to stop such unauthorized use and to cooperate with Us in any investigation of such unauthorized uses. We shall not under any circumstances be held liable for any claims related to the use or misuse of Your Participant Account due to the activities of any third party outside of our control or due to Your failure to maintain the confidentiality and security of Your Participant Account.</p>
<p style="color: #333333; font-family: \'Open Sans\', sans-serif; font-size: 14px; box-sizing: border-box; margin: 0px;">&nbsp;</p>
<p style="color: #333333; font-family: \'Open Sans\', sans-serif; font-size: 14px; box-sizing: border-box; margin: 0px;"><span style="box-sizing: border-box; font-weight: bold;">Content and Lecture Videos</span></p>
<p style="color: #333333; font-family: \'Open Sans\', sans-serif; font-size: 14px; box-sizing: border-box; margin: 0px;">&nbsp;</p>
<p style="color: #333333; font-family: \'Open Sans\', sans-serif; font-size: 14px; box-sizing: border-box; margin: 0px;">As a part of our Services offered through our Website, We shall grant you access to our content, Lecture Videos, and other information, documents, and data which may be in audio, video, written, graphic, recorded, photographic, or any machine-readable format in relation to the specific certification training course You have registered for ("Content and Lecture Videos").</p>
<p style="color: #333333; font-family: \'Open Sans\', sans-serif; font-size: 14px; box-sizing: border-box; margin: 0px;">&nbsp;</p>
<p style="color: #333333; font-family: \'Open Sans\', sans-serif; font-size: 14px; box-sizing: border-box; margin: 0px;">We reserve the right to amend, revise or update the Content and Lecture videos offered to You. In the event such an amendment, revision or updation occurs, You can access these, without any additional cost during the validity of the subscription.</p>
<p style="color: #333333; font-family: \'Open Sans\', sans-serif; font-size: 14px; box-sizing: border-box; margin: 0px;">&nbsp;</p>
<p style="color: #333333; font-family: \'Open Sans\', sans-serif; font-size: 14px; box-sizing: border-box; margin: 0px;"><span style="box-sizing: border-box; font-weight: bold;">Usage of the Website and Services</span></p>
<p style="color: #333333; font-family: \'Open Sans\', sans-serif; font-size: 14px; box-sizing: border-box; margin: 0px;">&nbsp;</p>
<p style="color: #333333; font-family: \'Open Sans\', sans-serif; font-size: 14px; box-sizing: border-box; margin: 0px;">We grant you a personal, restricted, non-transferable, non-exclusive, and revocable license to use the Website, the Services, and the Content and Lecture videos offered through the Website till the predefined time of the completion of the course that You have enrolled for or the termination of this Agreement according to the Terms and Conditions set forth herein, whichever is earlier. The Services and the Content and Lecture videos are provided solely for Your personal and non-commercial use to assist you in improving your knowledge or to make face the intended competitive exam or to keep you ahead of the rest. Under any circumstances, You cannot use it for commercial purposes.</p>
<p style="color: #333333; font-family: \'Open Sans\', sans-serif; font-size: 14px; box-sizing: border-box; margin: 0px;">&nbsp;</p>
<p style="color: #333333; font-family: \'Open Sans\', sans-serif; font-size: 14px; box-sizing: border-box; margin: 0px;">You are not permitted to reproduce, transmit, distribute, sub-license, broadcast, disseminate, or prepare derivative works of the Content and Lecture videos, or any part thereof, in any manner or through any communication channels or means, for any purpose other than the Restricted Purpose, without Our prior written consent.</p>
<p style="color: #333333; font-family: \'Open Sans\', sans-serif; font-size: 14px; box-sizing: border-box; margin: 0px;">&nbsp;</p>
<p style="color: #333333; font-family: \'Open Sans\', sans-serif; font-size: 14px; box-sizing: border-box; margin: 0px;"><span style="box-sizing: border-box; font-weight: bold;">Intellectual Property Rights</span></p>
<p style="color: #333333; font-family: \'Open Sans\', sans-serif; font-size: 14px; box-sizing: border-box; margin: 0px;">&nbsp;</p>
<p style="color: #333333; font-family: \'Open Sans\', sans-serif; font-size: 14px; box-sizing: border-box; margin: 0px;">While You are granted a limited and non-exclusive right to use the Website, the Services, and the Content and Lecture Videos for the Restricted Purpose as set forth in this Agreement, You acknowledge and agree that We are the sole and exclusive owner of the Website, the Services and the Content and Lecture videos and as such are vested with all Intellectual Property Rights and other proprietary rights in the Website, the Services, and the Content and Lecture videos.</p>
<p style="color: #333333; font-family: \'Open Sans\', sans-serif; font-size: 14px; box-sizing: border-box; margin: 0px;">&nbsp;</p>
<p style="color: #333333; font-family: \'Open Sans\', sans-serif; font-size: 14px; box-sizing: border-box; margin: 0px;">You acknowledge and agree that this Agreement other than permitting You to use the Website, the Services, and the Content and Lecture videos for the Restricted Purpose does not convey to You in any manner or form any right, title or interest of a proprietary, or any other nature in the Website, the Services, and the Content and Lecture videos.</p>
<p style="color: #333333; font-family: \'Open Sans\', sans-serif; font-size: 14px; box-sizing: border-box; margin: 0px;">&nbsp;</p>
<p style="color: #333333; font-family: \'Open Sans\', sans-serif; font-size: 14px; box-sizing: border-box; margin: 0px;"><span style="box-sizing: border-box; font-weight: bold;">Usage of Personal Information of Participants</span></p>
<p style="color: #333333; font-family: \'Open Sans\', sans-serif; font-size: 14px; box-sizing: border-box; margin: 0px;">&nbsp;</p>
<p style="color: #333333; font-family: \'Open Sans\', sans-serif; font-size: 14px; box-sizing: border-box; margin: 0px;">We reserve the right to feature Your picture in any photos, videos, or other promotional material used by Us. Further, We may use Your personal information to inform You about upcoming lecture videos offered by Us. However, We shall not distribute or share Your personal information with any third party marketing database or disclose Your personal information to any third party except on a case-to-case basis after proper verification of such third party or if required under any applicable law.</p>
<p style="color: #333333; font-family: \'Open Sans\', sans-serif; font-size: 14px; box-sizing: border-box; margin: 0px;">&nbsp;</p>
<p style="color: #333333; font-family: \'Open Sans\', sans-serif; font-size: 14px; box-sizing: border-box; margin: 0px;"><span style="box-sizing: border-box; font-weight: bold;">Limitation of Liability</span></p>
<p style="color: #333333; font-family: \'Open Sans\', sans-serif; font-size: 14px; box-sizing: border-box; margin: 0px;">&nbsp;</p>
<p style="color: #333333; font-family: \'Open Sans\', sans-serif; font-size: 14px; box-sizing: border-box; margin: 0px;">You expressly agree that use of the Website, the Services, and the Content and Lecture videos are at Your sole risk. The disclaimer of liability contained in this clause applies to any and all damages or injury caused by any failure of performance, error, omission, interruption, deletion, defect, delay in operation or transmission, computer virus, communication line failure, theft or destruction or unauthorized access to, alteration of, or use of records or any other material, whether for breach of contract, negligence, or under any other cause of action.</p>
<p style="color: #333333; font-family: \'Open Sans\', sans-serif; font-size: 14px; box-sizing: border-box; margin: 0px;">&nbsp;</p>
<p style="color: #333333; font-family: \'Open Sans\', sans-serif; font-size: 14px; box-sizing: border-box; margin: 0px;">You hereby specifically acknowledge that We are not liable for any defamatory, offensive, wrongful, or other users of the Website, the Services or the Content and Lecture videos and that the risk of damage or injury from the foregoing rests entirely with each user.</p>
<p style="color: #333333; font-family: \'Open Sans\', sans-serif; font-size: 14px; box-sizing: border-box; margin: 0px;">&nbsp;</p>
<p style="color: #333333; font-family: \'Open Sans\', sans-serif; font-size: 14px; box-sizing: border-box; margin: 0px;"><span style="box-sizing: border-box; font-weight: bold;">Term and Termination</span></p>
<p style="color: #333333; font-family: \'Open Sans\', sans-serif; font-size: 14px; box-sizing: border-box; margin: 0px;">&nbsp;</p>
<p style="color: #333333; font-family: \'Open Sans\', sans-serif; font-size: 14px; box-sizing: border-box; margin: 0px;">This Agreement will become effective upon Your acceptance of the terms of this Agreement by Your clicking on the "I ACCEPT" button and, subject to the terms and conditions of this Agreement, will remain in effect till You maintain a current, fully paid up online Participant Account, or until terminated by Us, whichever is earlier.</p>
<p style="color: #333333; font-family: \'Open Sans\', sans-serif; font-size: 14px; box-sizing: border-box; margin: 0px;">&nbsp;</p>
<p style="color: #333333; font-family: \'Open Sans\', sans-serif; font-size: 14px; box-sizing: border-box; margin: 0px;">We reserve the right to terminate this Agreement and block Your access to the Content and Lecture videos with immediate effect by sending a written notice through email to You to this effect ("Immediate Termination Date"), if such termination is made as a result of Your misrepresentation, default, misconduct, or breach of Your obligations related to or under this Agreement ("Event of Default"). On the occurrence of any Event of Default, We shall be authorized to exercise all the rights and remedies under this Agreement or applicable Law or available in equity to seek indemnification for any Loss or Claim resulting from any such Event of Default.</p>
<p style="color: #333333; font-family: \'Open Sans\', sans-serif; font-size: 14px; box-sizing: border-box; margin: 0px;">&nbsp;</p>
<p style="color: #333333; font-family: \'Open Sans\', sans-serif; font-size: 14px; box-sizing: border-box; margin: 0px;"><span style="box-sizing: border-box; font-weight: bold;">Indemnity</span></p>
<p style="color: #333333; font-family: \'Open Sans\', sans-serif; font-size: 14px; box-sizing: border-box; margin: 0px;">&nbsp;</p>
<p style="color: #333333; font-family: \'Open Sans\', sans-serif; font-size: 14px; box-sizing: border-box; margin: 0px;">You agree to indemnify and hold Us, Our contractors, licensors, directors, officers, employees, and agents, harmless from and against any and all claims, losses, damages, liabilities, and expenses including attorneys\' fees, arising out of Your unauthorized use of the Website, the Services, and the Content and Lecture videos or any violation or breach of this Agreement or any provisions hereof.</p>
<p style="color: #333333; font-family: \'Open Sans\', sans-serif; font-size: 14px; box-sizing: border-box; margin: 0px;">&nbsp;</p>
<p style="color: #333333; font-family: \'Open Sans\', sans-serif; font-size: 14px; box-sizing: border-box; margin: 0px;"><span style="box-sizing: border-box; font-weight: bold;">Waiver</span></p>
<p style="color: #333333; font-family: \'Open Sans\', sans-serif; font-size: 14px; box-sizing: border-box; margin: 0px;">&nbsp;</p>
<p style="color: #333333; font-family: \'Open Sans\', sans-serif; font-size: 14px; box-sizing: border-box; margin: 0px;">Neither failure nor delay on the part of any party to exercise any right, remedy, power, or privilege hereunder shall operate as a waiver thereof, or of the exercise of any other right, remedy, power, or privilege. No term of this Agreement shall be deemed waived, and no breach consented to, unless such waiver or consent shall be in writing and signed by the party claimed to have waived or consented. No waiver of any rights or consent to any breaches shall constitute a waiver of any other rights or consent to any other breach.</p>
<p style="color: #333333; font-family: \'Open Sans\', sans-serif; font-size: 14px; box-sizing: border-box; margin: 0px;">&nbsp;</p>
<p style="color: #333333; font-family: \'Open Sans\', sans-serif; font-size: 14px; box-sizing: border-box; margin: 0px;"><span style="box-sizing: border-box; font-weight: bold;">Severability</span></p>
<p style="color: #333333; font-family: \'Open Sans\', sans-serif; font-size: 14px; box-sizing: border-box; margin: 0px;">&nbsp;</p>
<p style="color: #333333; font-family: \'Open Sans\', sans-serif; font-size: 14px; box-sizing: border-box; margin: 0px;">In the event any provision of this Agreement is held invalid or unenforceable under the applicable laws of India, the remaining provisions shall continue in full force and effect, and the Agreement shall be deemed to be reformed by replacing such invalidated or unenforceable provision with a valid and enforceable provision that gives effect as closely as possible to the intentions of the parties as expressed by the invalidated or unenforceable provision.</p>
<p style="color: #333333; font-family: \'Open Sans\', sans-serif; font-size: 14px; box-sizing: border-box; margin: 0px;">&nbsp;</p>
<p style="color: #333333; font-family: \'Open Sans\', sans-serif; font-size: 14px; box-sizing: border-box; margin: 0px;"><span style="box-sizing: border-box; font-weight: bold;">Amendment and Assignment</span></p>
<p style="color: #333333; font-family: \'Open Sans\', sans-serif; font-size: 14px; box-sizing: border-box; margin: 0px;">&nbsp;</p>
<p style="color: #333333; font-family: \'Open Sans\', sans-serif; font-size: 14px; box-sizing: border-box; margin: 0px;">We reserve the right to unilaterally amend or modify this Agreement without giving any prior notification to You. We shall however publish the revised agreement on the Website so that You are aware of the revisions, modifications and amendments made by Us to this Agreement. You acknowledge and agree that it is Your responsibility to check the Website periodically for any revisions, modifications, and amendments. Your continued use of or access to the Website, the Services, and the Content and Lecture videos following the posting of any changes to this Agreement shall constitute acceptance of those changes.</p>
<p style="color: #333333; font-family: \'Open Sans\', sans-serif; font-size: 14px; box-sizing: border-box; margin: 0px;">&nbsp;</p>
<p style="color: #333333; font-family: \'Open Sans\', sans-serif; font-size: 14px; box-sizing: border-box; margin: 0px;">You are not permitted to assign this Agreement or the rights and obligations mentioned in this Agreement to any third party and You only shall be held liable for any breach of this Agreement or any terms and conditions hereof.</p>
<p style="color: #333333; font-family: \'Open Sans\', sans-serif; font-size: 14px; box-sizing: border-box; margin: 0px;">&nbsp;</p>
<p style="color: #333333; font-family: \'Open Sans\', sans-serif; font-size: 14px; box-sizing: border-box; margin: 0px;"><span style="box-sizing: border-box; font-weight: bold;">Entire Agreement</span></p>
<p style="color: #333333; font-family: \'Open Sans\', sans-serif; font-size: 14px; box-sizing: border-box; margin: 0px;">&nbsp;</p>
<p style="color: #333333; font-family: \'Open Sans\', sans-serif; font-size: 14px; box-sizing: border-box; margin: 0px;">This Agreement, along with the Privacy Policy, Refund Policy, Rescheduling Policy, Terms of Use, and any additional guidelines, rules, and/or disclaimers posted on the Website constitutes the entire agreement governing Your use of our Website and supersedes any prior agreements, if any, relating to any matter dealt within this Agreement.</p>
<p style="color: #333333; font-family: \'Open Sans\', sans-serif; font-size: 14px; box-sizing: border-box; margin: 0px;">&nbsp;</p>
<p style="color: #333333; font-family: \'Open Sans\', sans-serif; font-size: 14px; box-sizing: border-box; margin: 0px;">Note: By clicking &ldquo;I Agree&rdquo; button, You are agreeing to all our Policies as listed in the website.</p>',
                        'is_active'  => 1,
                        'creator_id' => 0,
                        'updator_id' => 0,
                        'created_at' => Carbon::now()->toDateTimeString(),
                        'updated_at' => Carbon::now()->toDateTimeString(),
                    ]
                ]
            );

        }
    }
}